version: '3.0'

services:
  rasa:
    image: rasa/rasa:2.6.3-full
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./rasa-app-data/:/app/"
    command:
    - run

  action_server:
    image: rasa/rasa-sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./actions:/app/actions"

networks: {rasa-network: {}}
